-- Create users table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id BIGINT NOT NULL UNIQUE,
    username VARCHAR,
    first_name VARCHAR,
    current_weight DECIMAL,
    height DECIMAL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE INDEX idx_users_telegram_id ON users(telegram_id);

-- Create exercises table
CREATE TABLE exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    description TEXT,
    muscle_group VARCHAR NOT NULL,
    exercise_type VARCHAR NOT NULL,
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    creator_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_exercises_creator FOREIGN KEY (creator_id) REFERENCES users(id)
);

CREATE INDEX idx_exercises_is_system ON exercises(is_system);

-- Create workouts table
CREATE TABLE workouts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR,
    started_at TIMESTAMP NOT NULL,
    ended_at TIMESTAMP,
    status VARCHAR DEFAULT 'IN_PROGRESS',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_workouts_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_workouts_user_id ON workouts(user_id);

-- Create workout_exercises table
CREATE TABLE workout_exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_id BIGINT NOT NULL,
    exercise_id BIGINT NOT NULL,
    order_index INTEGER NOT NULL,
    notes TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_workout_exercises_workout FOREIGN KEY (workout_id) REFERENCES workouts(id) ON DELETE CASCADE,
    CONSTRAINT fk_workout_exercises_exercise FOREIGN KEY (exercise_id) REFERENCES exercises(id)
);

-- Create workout_sets table
CREATE TABLE workout_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_exercise_id BIGINT NOT NULL,
    set_number INTEGER NOT NULL,
    weight DECIMAL,
    reps INTEGER,
    duration_seconds INTEGER,
    rpe INTEGER,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_workout_sets_workout_exercise FOREIGN KEY (workout_exercise_id) REFERENCES workout_exercises(id) ON DELETE CASCADE
);
